version: '3.8'

services:
  rpa-mit-approvals:
    build:
      context: .
      target: production
    image: rpa-mit-approvals
    container_name: rpa-mit-approvals
    environment:
      COMPlus_EnableDiagnostics: 0
      POSTGRES_HOST: ${POSTGRES_HOST:-est-mit-approvals-postgres}
      POSTGRES_DB: rpa_mit_approvals
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-password}
      POSTGRES_PORT: "5432"
      SCHEMA_DEFAULT: ${POSTGRES_SCHEMA_NAME:-public}
    ports:
      - "3000:3000"
